// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// score
double score(NumericVector g, NumericVector y, NumericVector w, int n, NumericVector group, double theta);
RcppExport SEXP clogitboost_score(SEXP gSEXP, SEXP ySEXP, SEXP wSEXP, SEXP nSEXP, SEXP groupSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    __result = Rcpp::wrap(score(g, y, w, n, group, theta));
    return __result;
END_RCPP
}
// seconddev
double seconddev(NumericVector g, NumericVector y, NumericVector w, int n, NumericVector group, double theta);
RcppExport SEXP clogitboost_seconddev(SEXP gSEXP, SEXP ySEXP, SEXP wSEXP, SEXP nSEXP, SEXP groupSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    __result = Rcpp::wrap(seconddev(g, y, w, n, group, theta));
    return __result;
END_RCPP
}
// persamplegrad
NumericVector persamplegrad(NumericVector fx, NumericVector y, int n, NumericVector group);
RcppExport SEXP clogitboost_persamplegrad(SEXP fxSEXP, SEXP ySEXP, SEXP nSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type fx(fxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group(groupSEXP);
    __result = Rcpp::wrap(persamplegrad(fx, y, n, group));
    return __result;
END_RCPP
}
// likelihood
double likelihood(NumericVector fx, NumericVector y, int n, NumericVector group);
RcppExport SEXP clogitboost_likelihood(SEXP fxSEXP, SEXP ySEXP, SEXP nSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type fx(fxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group(groupSEXP);
    __result = Rcpp::wrap(likelihood(fx, y, n, group));
    return __result;
END_RCPP
}
